aquecimento:
	mkdir -p bin
	nvcc aquecimento.cu -o bin/aquecimento

matriz:
	mkdir -p bin
	nvcc matriz.cu -o bin/matriz

complex:
	mkdir -p bin
	nvcc complex.cu -o bin/complex

simple:
	mkdir -p bin
	nvcc simple.cu -o bin/simple

clear:
	rm -r -f bin
